DRAFT: Bilinear Remapping
UXARRAY/uxarray pull request #1016
Opened 2024-10-14 19:17 UTC by aaronzedwick

Closes #678 

## Overview

Adds bilinear remapping functionality to UXarray.
## Expected Usage

```Python
import uxarray as ux

source = "/path"
destination = "/path"
source_uxds = ux.open_dataset(destination, destination)
destination = ux.open_dataset(destination, destination)

bilinear_remap = source_uxds.remap.bilinear(destination.uxgrid, remap_to='face centers',
                                                       coord_type='cartesian')

```

## PR Checklist

**General**
- [x] An issue is linked created and linked
- [x] Add appropriate labels
- [x] Filled out Overview and Expected Usage (if applicable) sections

**Testing**
- [ ] Adequate tests are created if there is new functionality
- [ ] Tests cover all possible logical paths in your function
- [ ] Tests are not too basic (such as simply calling a function and nothing else)

**Documentation**
- [ ] Docstrings have been added to all new functions
- [ ] Docstrings have updated with any function changes
- [ ] Internal functions have a preceding underscore (`_`) and have been added to `docs/internal_api/index.rst`
- [ ] User functions have been added to `docs/user_api/index.rst`

2024-10-17 23:04 UTC, ahijevyc commented on uxarray/remap/bilinear.py
> +    lat0, lon0 = np.radians(lat0), np.radians(lat0)
is this a typo?
lon0 should equal np.radians(lon0), right?

2025-03-11 18:01 UTC, philipc2 commented
Once this is implemented, @rajeeja this would be a good place to compare our implementation to the one in ESMF.

2025-03-24 16:24 UTC, philipc2 requested changes
Typo in the user guide. 

![image](https://github.com/user-attachments/assets/d8c9eb46-559c-4922-88e5-cc990566f7d4)

2025-03-24 16:24 UTC, philipc2 commented on uxarray/grid/geometry.py
> +def barycentric_coordinates_cartesian(polygon, point):
Please use Numba

2025-03-24 16:24 UTC, philipc2 commented on uxarray/grid/neighbors.py
> +# @njit(cache=True)
Is this intentional?

2025-03-24 16:56 UTC, aaronzedwick commented on uxarray/grid/neighbors.py
> +# @njit(cache=True)
Oh no, that was leftover from error debugging, I will fix that. Thanks for the catch.

2025-04-12 01:20 UTC, rajeeja commented
Thanks for the changes: triangles and faces that don't have data show something still for:
<img width="491" alt="Screenshot 2025-04-11 at 20 18 36" src="https://github.com/user-attachments/assets/85ed3ded-b7fa-4509-884b-4910ea149aed" />

nearest neighbor

<img width="599" alt="Screenshot 2025-04-11 at 20 15 37" src="https://github.com/user-attachments/assets/53ef4b48-8143-4488-9a51-877558e4a4e2" />

inverse_distance_weight

<img width="752" alt="Screenshot 2025-04-11 at 20 16 27" src="https://github.com/user-attachments/assets/d4956090-5683-49f3-afe9-881607678dc0" />

bilinear seems to work correctly now.

2025-04-12 01:30 UTC, rajeeja commented
Testing an example inspired from https://github.com/esmf-org/esmf/blob/develop/src/addon/esmpy/examples/notebooks/Periodic.ipynb (our mesh has no periodicity unlike this one)

bilinear is generating correct results, horizontal black lines are gone, vertical ones are still there but that is expected

```
lon_in = np.arange(-175, 175.1, 10)
lat_in = np.arange(-88, 88.1, 4)
lon_out = np.arange(-177.5, 177.5 + 0.1, 5)
lat_out = np.arange(-88, 88.1, 4) 
```

```
remapped_da = ux_source_da.remap.bilinear(
    ux_grid_out, 
    remap_to="face centers" # Output data will be located at destination face centers
)
```

lon range for out mesh has higher range.
<img width="691" alt="Screenshot 2025-04-11 at 20 28 55" src="https://github.com/user-attachments/assets/b1575fff-675d-47bb-9375-2cda280fd123" />

2025-04-12 03:26 UTC, aaronzedwick commented
> Thanks for the changes: triangles and faces that don't have data show something still for: <img alt="Screenshot 2025-04-11 at 20 18 36" width="491" src="https://private-user-images.githubusercontent.com/1466114/432992942-85ed3ded-b7fa-4509-884b-4910ea149aed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ0Mjg2NDIsIm5iZiI6MTc0NDQyODM0MiwicGF0aCI6Ii8xNDY2MTE0LzQzMjk5Mjk0Mi04NWVkM2RlZC1iN2ZhLTQ1MDktODg0Yi00OTEwZWExNDlhZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MTJUMDMyNTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODY1NTU0YjRiY2ZhZWIyMDhkODhjZjZiMGU4ODA4YTVmNjVlYTQwMGUxYzQ1ZTJiN2Y4NWY5NjMzNzQ0ODMwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.r_HYrrMKrdpEsjOeMCX6I00RAdSKZMSc76-gUwiQSdc">
> 
> nearest neighbor
> 
> <img alt="Screenshot 2025-04-11 at 20 15 37" width="599" src="https://private-user-images.githubusercontent.com/1466114/432992701-53ef4b48-8143-4488-9a51-877558e4a4e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ0Mjg2NDIsIm5iZiI6MTc0NDQyODM0MiwicGF0aCI6Ii8xNDY2MTE0LzQzMjk5MjcwMS01M2VmNGI0OC04MTQzLTQ0ODgtOWE1MS04Nzc1NThlNGE0ZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MTJUMDMyNTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZjNzQ0YzVlMjAxZGQwNTM3Y2E1Mjg3NTQyNmM2MWFiYjRkMGFjZDZiNDI5ZmE5ZGFlOWI1ZGFhOWVlMDMxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QBRLUDRVPOc9Y4oJ3JovTghU2EbfG4KZwBecc9ffuW0">
> inverse_distance_weight
> 
> <img alt="Screenshot 2025-04-11 at 20 16 27" width="752" src="https://private-user-images.githubusercontent.com/1466114/432992710-d4956090-5683-49f3-afe9-881607678dc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ0Mjg2NDIsIm5iZiI6MTc0NDQyODM0MiwicGF0aCI6Ii8xNDY2MTE0LzQzMjk5MjcxMC1kNDk1NjA5MC01NjgzLTQ5ZjMtYWZlOS04ODE2MDc2NzhkYzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MTJUMDMyNTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODg5NmE1M2YwNDEyMGQxNjMzZGMzODAyOGExZWE2YzA2ZDA2NDBkNjU0Y2U3NjM2MWFmOWQzYTUzZjE4ZjhmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.EUfs28lH10Sr6NHsBtK3bC_-3JW1Xe34Bswpnbsig8Q">
> bilinear seems to work correctly now.

Yup, thanks for pointing this out! Will fix the same issue in NN and IDW in another PR.

2025-04-12 03:28 UTC, aaronzedwick commented
> Testing an example inspired from https://github.com/esmf-org/esmf/blob/develop/src/addon/esmpy/examples/notebooks/Periodic.ipynb (our mesh has no periodicity unlike this one)
> 
> bilinear is generating correct results, horizontal black lines are gone, vertical ones are still there but that is expected
> 
> ```
> lon_in = np.arange(-175, 175.1, 10)
> lat_in = np.arange(-88, 88.1, 4)
> lon_out = np.arange(-177.5, 177.5 + 0.1, 5)
> lat_out = np.arange(-88, 88.1, 4) 
> ```
> 
>  ```
> remapped_da = ux_source_da.remap.bilinear(
>     ux_grid_out, 
>     remap_to="face centers" # Output data will be located at destination face centers
> )
> ```
> 
> lon range for out mesh has higher range. <img alt="Screenshot 2025-04-11 at 20 28 55" width="691" src="https://private-user-images.githubusercontent.com/1466114/432993534-b1575fff-675d-47bb-9375-2cda280fd123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ0Mjg2NDIsIm5iZiI6MTc0NDQyODM0MiwicGF0aCI6Ii8xNDY2MTE0LzQzMjk5MzUzNC1iMTU3NWZmZi02NzVkLTQ3YmItOTM3NS0yY2RhMjgwZmQxMjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MTJUMDMyNTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2Q1YTFiMmUzNjhlN2FkMjM3MmVlYTY5OTQwM2ZiZDQ4YmViZDg0ZmEwMGZmYTI2MzBjZTU0MTExODg1YzMxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.v_pmVbgGPoxBXFvi1d_F9jNxoIh0yMJmKixI6bTUu88">

This is great! Thanks @rajeeja!

2025-04-17 03:06 UTC, philipc2 requested changes
Notebook appears to be timing out.

https://uxarray--1016.org.readthedocs.build/en/1016/user-guide/remapping.html#id3

2025-04-17 12:17 UTC, aaronzedwick commented
> Notebook appears to be timing out.
> 
> https://uxarray--1016.org.readthedocs.build/en/1016/user-guide/remapping.html#id3

Yeah, working on that.

2025-04-17 16:42 UTC, philipc2 commented
@rajeeja @aaronzedwick 

Have either of you had a chance to run a comparison to the results from TempestRemap?

2025-04-17 20:27 UTC, aaronzedwick commented
> @rajeeja @aaronzedwick
> 
> Have either of you had a chance to run a comparison to the results from TempestRemap?

@rajeeja created an example using ESMPy, which uses TempestRemap for it's bilinear interpolation.

2025-04-17 20:40 UTC, philipc2 commented
> > @rajeeja @aaronzedwick
> > Have either of you had a chance to run a comparison to the results from TempestRemap?
> 
> @rajeeja created an example using ESMPy, which uses TempestRemap for its bilinear interpolation.

The example above seems to be on a basic unstructured grid. Have we done a comparison between unstructured grids?

2025-04-17 21:00 UTC, aaronzedwick commented
> > > @rajeeja @aaronzedwick
> > > Have either of you had a chance to run a comparison to the results from TempestRemap?
> > 
> > 
> > @rajeeja created an example using ESMPy, which uses TempestRemap for its bilinear interpolation.
> 
> The example above seems to be on a basic unstructured grid. Have we done a comparison between unstructured grids?

That wasn't the comparison; that was showcasing our remapping on a grid that was slightly larger. However, I think he used the same file for the comparison. Rajeev mentioned that he was going to get actual grid data to load for the comparison, not sure if he ended up doing that @rajeeja. The issue is getting ESMPy and UXarray to both load the same files. I think Rajeev was having struggles with getting UXarray to load the files inside the ESMPy docs.

2025-04-23 17:27 UTC, rajeeja commented
@aaronzedwick this one took 42 mins https://github.com/UXARRAY/uxarray/actions/runs/14623421875/job/41029024529?pr=1016

2025-04-23 17:43 UTC, rajeeja commented
> @aaronzedwick this one took 42 mins https://github.com/UXARRAY/uxarray/actions/runs/14623421875/job/41029024529?pr=1016

would it be good to shorten the test case in the notebook?

2025-04-23 18:37 UTC, aaronzedwick commented
> > @aaronzedwick this one took 42 mins https://github.com/UXARRAY/uxarray/actions/runs/14623421875/job/41029024529?pr=1016
> 
> would it be good to shorten the test case in the notebook?

We could, but it doesn't seem that much longer than what other PR's are taking for tests. It is only a few minutes longer. And when RTree is implemented, that should give a significant boost to performance, which should solve the extra few minutes it takes.

2025-04-24 16:29 UTC, rajeeja commented
> > > > @rajeeja @aaronzedwick
> > > > Have either of you had a chance to run a comparison to the results from TempestRemap?
> > > 
> > > 
> > > @rajeeja created an example using ESMPy, which uses TempestRemap for its bilinear interpolation.
> > 
> > 
> > The example above seems to be on a basic unstructured grid. Have we done a comparison between unstructured grids?
> 
> That wasn't the comparison; that was showcasing our remapping on a grid that was slightly larger. However, I think he used the same file for the comparison. Rajeev mentioned that he was going to get actual grid data to load for the comparison, not sure if he ended up doing that @rajeeja. The issue is getting ESMPy and UXarray to both load the same files. I think Rajeev was having struggles with getting UXarray to load the files inside the ESMPy docs.
> 
> @rajeeja, if you did end up getting the comparison, can you post a photo here? If not, I can look into finding something that would work if you want me to. I would have to install ESMPy on my machine, however.

https://github.com/rajeeja/uxarray_squadgen/blob/main/tempestremap_uxarray/remap_comparison_report.md#histogram-and-scatter-plot-of-remapping-differences

2025-04-24 16:30 UTC, rajeeja approved these changes
tempestremap comparison looks good. code for comparison here: https://github.com/rajeeja/uxarray_squadgen/tree/main/tempestremap_uxarray

2025-04-24 17:11 UTC, aaronzedwick commented
> tempestremap comparison looks good. code for comparison here: https://github.com/rajeeja/uxarray_squadgen/tree/main/tempestremap_uxarray

This looks great, thanks for doing this!

2025-04-25 16:30 UTC, philipc2 commented
@rajeeja 

Thank you for putting this report together!

Do we know where the differences are coming from? A max difference of `1e-2` is quite a bit larger than what I would expect. 

Looking at the UXarray and TempestRemap plots, the UXarray one has a noticeable jitter 

![image](https://github.com/user-attachments/assets/fa8c9c32-9029-46b9-804a-a7a4831c1efb)

For example

![image](https://github.com/user-attachments/assets/96ae0811-849e-4ae5-a7c3-17d0056c29a3)

Compared to

![image](https://github.com/user-attachments/assets/a7979738-903e-4b17-b0c0-b2463ca295d6)

Can you generate a plot of the following
- Absolute Difference between TempestRemap and UXarray at each cell

2025-04-25 16:46 UTC, aaronzedwick commented
The differences could be that tempest remap  splits bigger polygons into triangles and finds the sub triangle that holds the point. It then does the barycentric calculation with that triangle. I tried to emulate the current barycentric implementation that spatial hashing uses, by just getting the weights of the entire polygon without finding the sub triangle the point is in, thus eliminating the extra check to point in polygon. In my mind the performance at the time was worth it. However now that I have done some benchmarks, point in polygon is actually very lightweight. I don’t think it would have a massive impact if we changed to check the sub triangles. However, it would cause more calls to point in polygon. For example, a mesh with any given polygon would have (n_edges-2) * n_face calls to point in polygon. Like I said though, I believe the function takes a very small amount of time even with the current calls (n_face best case). Let me know what you think @philipc2

2025-05-02 14:16 UTC, rajeeja commented
With new changes:

UXARRAY mean: 1.9997, std: 0.4955
TEMPEST mean: 2.0000, std: 0.4963
Mean abs diff: 0.002161
Max abs diff: 0.363508

![a](https://github.com/user-attachments/assets/d2f9760d-09ad-46e1-bf9b-7e93e5feda41)
![b](https://github.com/user-attachments/assets/47aabfa4-e294-49dc-aa49-333ac10a47eb)

2025-05-08 16:08 UTC, rajeeja commented
@aaronzedwick can you push the latest changes that make it same as tempestremap?

2025-05-08 18:40 UTC, aaronzedwick commented
> @aaronzedwick can you push the latest changes that make it same as tempestremap?

I already have.

2025-05-15 19:19 UTC, rajeeja commented
@philipc2 seems like noise now see 1e-7 on x-axis https://github.com/rajeeja/uxarray_squadgen/blob/main/tempestremap_uxarray/remap_comparison.png

2025-05-16 03:10 UTC, philipc2 commented
With the latest changes, doing the following remapping:

```
Source Cells: 655,362 (MPAS)
Destination Cells: 196,608 (HEALPix)
```

<img width="1298" alt="image" src="https://github.com/user-attachments/assets/e187c4d9-6983-4f51-9b11-d6c68f4be72f" />


Much better performance, but still a significant slowdown when constructing the weights.

Is it possible to write the entire weight computation in Numba?

We can do a single query for the points in face outside of Numba and pass those values in.

2025-05-16 10:56 UTC, aaronzedwick commented
> With the latest changes, doing the following remapping:
> 
> ```
> Source Cells: 655,362 (MPAS)
> Destination Cells: 196,608 (HEALPix)
> ```
> 
> <img alt="image" width="1298" src="https://private-user-images.githubusercontent.com/67855069/444362270-e187c4d9-6983-4f51-9b11-d6c68f4be72f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDczOTI4NDYsIm5iZiI6MTc0NzM5MjU0NiwicGF0aCI6Ii82Nzg1NTA2OS80NDQzNjIyNzAtZTE4N2M0ZDktNjk4My00ZjUxLTliMTEtZDZjNjhmNGJlNzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTE2VDEwNDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZTU1NTcxOGJkNzBmMTc3OGI4OGI4NmE5MDc0ZjJhNTc5ZjQ4ZjVlZjZkMWIxOTE2OTYzODFkNzE4N2NhM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1yeKyaStrOYahNwuPdvWPRmAJlQYBsqcHE3ujxApy78">
> Much better performance, but still not really usable for any of our higher resolution grids.
> 
> Is it possible to write the entire weight computation in Numba?
> 
> We can do a single query for the points in face outside of Numba and pass those values in.

Yeah, that was the plan once the point in face query was able to be done in one query. I wanted to make sure my implementation was accurate before worrying about numba, since it wasn’t wanting to work with my first implementation. I’ll start working on performance now that the point in face bottleneck is fixed. I see you made the newton quadrilateral function use numba already, thanks! I’m still learning how to write everything to be compatible with numba. Not always easy!

2025-05-21 03:07 UTC, philipc2 approved these changes
Fantastic work @aaronzedwick 

The results look excellent and the performance is really good. Takes about `30s` to go from a 15km MPAS grid to a HEALPix zoom of 8 on my laptop.

There may be some opportunities for some smaller optimizations later, and to expose the weights to the user to allow them to store and reuse them, but for now this is looking great.

2025-05-21 04:35 UTC, merged