User Guide for from_file function
UXARRAY/uxarray pull request #1047
Opened 2024-10-29 15:45 UTC by rajeeja

Users guide for using from_file GRID function

2024-10-29 16:12 UTC, philipc2 commented
Do you have any files from climate models or similar that you should showcase in this notebook? I'm not sure if showcasing the `multipoly.shp` is relevant to our users, as it isn't a proper grid.

2024-10-29 16:54 UTC, rajeeja commented
> Do you have any files from climate models or similar that you should showcase in this notebook? I'm not sure if showcasing the `multipoly.shp` is relevant to our users, as it isn't a proper grid.

yes, this PR is work in progress. I'll make it a draft.

2024-11-11 16:15 UTC, aaronzedwick commented
@philipc2 Do you know why the docs are different than the actual notebook? You can compare on reviewNB, the notebook is different on the docs site.

2024-11-12 18:02 UTC, rajeeja commented
> @philipc2 Do you know why the docs are different than the actual notebook? You can compare on reviewNB, the notebook is different on the docs site. 

Can you give the two links? 

There's only a python version change here, right? :
docs/user-guide/from-points.ipynb

2024-11-12 18:57 UTC, aaronzedwick commented
> > @philipc2 Do you know why the docs are different than the actual notebook? You can compare on reviewNB, the notebook is different on the docs site.
> 
> Can you give the two links?
> 
> There's only a python version change here, right? : docs/user-guide/from-points.ipynb

That isn't the notebook I am talking about, I am looking at the from_file notebook. The bug is fixed now though.

2024-11-15 23:37 UTC, rajeeja commented on docs/userguide.rst
> +
Done

2024-11-16 20:04 UTC, philipc2 commented on docs/userguide.rst
> + Load unstructured grids using the Grid from_file function
This looks to have rendered incorrectly on the docs.

![image](https://github.com/user-attachments/assets/3dad29ec-d9cd-41e3-b651-4b52251cd757)

2024-11-18 15:24 UTC, philipc2 commented
![image](https://github.com/user-attachments/assets/e8211a6a-a364-4786-bc71-3518a7dc221b)

What about the following title & description?
#### Title
Reading & Working with Geometry Files

#### Description
Load and work with geometry files (i.e. Shapefile)

2024-11-18 16:29 UTC, rajeeja commented
> ![image](https://private-user-images.githubusercontent.com/67855069/387280012-e8211a6a-a364-4786-bc71-3518a7dc221b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDcyMTQsIm5iZiI6MTczMTk0NjkxNCwicGF0aCI6Ii82Nzg1NTA2OS8zODcyODAwMTItZTgyMTFhNmEtYTM2NC00Nzg2LWJjNzEtMzUxOGE3ZGMyMjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDE2MjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZWJkN2VlNDU0NDMwNzc5ZTA3ZjMzYWM4N2VkYjEzYjI2MTg0Y2UwYzU4MWFhNWJmZjY1Mjk4MGVmZmI3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kv28U6-wmQlbHv9HIMiuBdNP3Nwzp-HuKWT2Fgu5MHc)
> 
> What about the following title & description?
> 
> #### Title
> Reading & Working with Geometry Files
> 
> #### Description
> Load and work with geometry files (i.e. Shapefile, GeoJSON)

Is GIS more accurate? (it's gray area as we may also call it geometry in the sense that they store spatial data, such as the shapes, boundaries, and locations of features on the Earth’s surface.

2024-11-26 16:21 UTC, philipc2 commented
> > ![image](https://private-user-images.githubusercontent.com/67855069/387280012-e8211a6a-a364-4786-bc71-3518a7dc221b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDcyMTQsIm5iZiI6MTczMTk0NjkxNCwicGF0aCI6Ii82Nzg1NTA2OS8zODcyODAwMTItZTgyMTFhNmEtYTM2NC00Nzg2LWJjNzEtMzUxOGE3ZGMyMjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDE2MjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZWJkN2VlNDU0NDMwNzc5ZTA3ZjMzYWM4N2VkYjEzYjI2MTg0Y2UwYzU4MWFhNWJmZjY1Mjk4MGVmZmI3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kv28U6-wmQlbHv9HIMiuBdNP3Nwzp-HuKWT2Fgu5MHc)
> > What about the following title & description?
> > #### Title
> > Reading & Working with Geometry Files
> > #### Description
> > Load and work with geometry files (i.e. Shapefile, GeoJSON)
> 
> Is GIS more accurate? (it's gray area as we may also call it geometry in the sense that they store spatial data, such as the shapes, boundaries, and locations of features on the Earth’s surface.

It might be a bit more accurate, but GIS seems pretty outside of the scope of our package.

2024-11-27 17:19 UTC, rajeeja commented
> > > ![image](https://private-user-images.githubusercontent.com/67855069/387280012-e8211a6a-a364-4786-bc71-3518a7dc221b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDcyMTQsIm5iZiI6MTczMTk0NjkxNCwicGF0aCI6Ii82Nzg1NTA2OS8zODcyODAwMTItZTgyMTFhNmEtYTM2NC00Nzg2LWJjNzEtMzUxOGE3ZGMyMjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDE2MjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZWJkN2VlNDU0NDMwNzc5ZTA3ZjMzYWM4N2VkYjEzYjI2MTg0Y2UwYzU4MWFhNWJmZjY1Mjk4MGVmZmI3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kv28U6-wmQlbHv9HIMiuBdNP3Nwzp-HuKWT2Fgu5MHc)
> > > What about the following title & description?
> > > #### Title
> > > Reading & Working with Geometry Files
> > > #### Description
> > > Load and work with geometry files (i.e. Shapefile, GeoJSON)
> > 
> > 
> > Is GIS more accurate? (it's gray area as we may also call it geometry in the sense that they store spatial data, such as the shapes, boundaries, and locations of features on the Earth’s surface.
> 
> It might be a bit more accurate, but GIS seems pretty outside of the scope of our package.

Ok, since we explicitly call the formats, I have changed it to geometry files "Shapefile, GeoJSON"

2024-12-06 20:03 UTC, rajeeja commented on uxarray/grid/grid.py
> +            return cls.from_dataset(dataset)
Yes, that makes more sense. Thanks for the suggestion.

2025-01-09 19:53 UTC, aaronzedwick reviewed
I think you forgot to clear the cell output and restart the kernel of the notebook before pushing the changes. Also, there seems to be an error in the docs.

2025-01-10 21:53 UTC, rajeeja commented
> I think you forgot to clear the cell output and restart the kernel of the notebook before pushing the changes. Also, there seems to be an error in the docs.

Thanks, yes. I'm looking to fix this.

2025-01-10 23:58 UTC, philipc2 requested changes
Notebook looks great. Mostly formatting comments below.

2025-01-13 22:14 UTC, philipc2 approved these changes
Notebook looks good now! 

Feel free to go ahead and merge @rajeeja

2025-01-13 23:35 UTC, merged