DRAFT: area correction for when an edge is the line of constant lattitude
UXARRAY/uxarray pull request #1120
Opened 2024-12-23 18:27 UTC by rajeeja

2025-01-03 17:39 UTC, rajeeja commented
@hongyuchen1030 [area correction calc](https://github.com/UXARRAY/uxarray/pull/1120/files#diff-46dc8049509f725d0b3000ee27a346e80821efc4b179a811766bb8716a9182a1R212) function is ready (computes the correction correctly - more on exposure via interface is needed), how would this be used and what interface do you require for zonal averaging?

2025-01-03 18:11 UTC, philipc2 commented
@rajeeja 

Have you had a chance to test the performance of this implementation?

2025-01-03 18:19 UTC, rajeeja commented
No, I was focussed on getting correct result at this point.

2025-01-03 18:20 UTC, philipc2 commented
> No, I was focussed on getting correct result at this point.

Would you like me take a look at the performance and report back?

2025-01-03 18:21 UTC, philipc2 commented on uxarray/grid/area.py
> +        x, y, z = x_cartesian, y_cartesian, z_cartesian
I'd suggest passing in `Grid.node_x`, `Grid.node_y` and `Grid.node_z` into this function directly to avoid needing to re-compute it.

2025-01-03 18:25 UTC, philipc2 reviewed
May you add some tests & consider adding a blurb in the "[Face Area Calculations](https://uxarray.readthedocs.io/en/latest/user-guide/area_calc.html)" user guide.

2025-01-08 05:58 UTC, philipc2 requested changes
Nice work.

There are a few formatting issues in the rendered notebook.

https://uxarray--1120.org.readthedocs.build/en/1120/user-guide/area_calc.html

2025-01-08 05:58 UTC, philipc2 commented on uxarray/grid/grid.py
> +        correct_area: Optional[bool] = False,
Should we default to `True`?

2025-01-08 05:58 UTC, philipc2 commented on uxarray/grid/area.py
> +        return False  # Or handle it according to your specific needs
```suggestion
        return False  
```

2025-01-08 05:58 UTC, philipc2 commented on uxarray/grid/area.py
> +    # North and South Pole vectors (make them float64)
```suggestion
    # North and South Pole vectors
```

2025-01-08 05:58 UTC, philipc2 commented on uxarray/grid/area.py
> +    p_north = np.array([0.0, 0.0, 1.0])  # Changed to float64
```suggestion
    p_north = np.array([0.0, 0.0, 1.0])  
```

2025-01-08 05:58 UTC, philipc2 commented on uxarray/grid/area.py
> +    p_south = np.array([0.0, 0.0, -1.0])  # Changed to float64
```suggestion
    p_south = np.array([0.0, 0.0, -1.0])  
```

2025-01-08 05:58 UTC, philipc2 commented on uxarray/grid/area.py
> +    # TODO: Fix sign of the calculated correction?
Has this been addressed?

2025-01-08 05:58 UTC, philipc2 commented on test/test_grid.py
Do we have any references face areas that we can compare our implementation too? Could be worth adding a test if we do.

2025-01-08 17:08 UTC, rajeeja commented on uxarray/grid/grid.py
> +        correct_area: Optional[bool] = False,
I don't think so as this is very compute intensive and will increase our testing time by a lot.

2025-01-08 17:11 UTC, rajeeja commented on test/test_grid.py
No, we don't - I'll look for one.

2025-01-17 11:12 UTC, rajeeja commented on uxarray/grid/area.py
> +    # TODO: Fix sign of the calculated correction?
> Has this been addressed?

No, it is based on northern and southern hemisphere and edge orientation, will add soon

2025-02-11 16:14 UTC, philipc2 commented
Equation looks good now!

![image](https://github.com/user-attachments/assets/2be92e1f-7d15-4564-aa77-40954f202fb8)

2025-02-11 16:17 UTC, philipc2 commented on uxarray/grid/area.py
> +                    print("Edge is in the ", hemisphere, " hemisphere.")
```suggestion
```

2025-02-11 16:17 UTC, philipc2 commented on uxarray/grid/area.py
> +                )
```suggestion
```

2025-02-11 16:17 UTC, philipc2 commented on uxarray/grid/area.py
> +        print("AREA Before Correction", area)
```suggestion
```

2025-02-11 16:18 UTC, philipc2 commented on uxarray/grid/area.py
> +        print("AREA After Correction", area)
```suggestion
```

2025-02-11 16:20 UTC, philipc2 commented on uxarray/grid/area.py
> +    correct_area=False,
Please add this to the docstring.

2025-02-11 16:21 UTC, philipc2 commented on uxarray/grid/area.py
> +    correct_area=False,
Please add this to the docstring.

2025-02-11 16:22 UTC, philipc2 commented on uxarray/grid/grid.py
> +        correct_area: Optional[bool] = False,
Can you share some profile results using this [grid](https://github.com/ProjectPythia/unstructured-grid-viz-cookbook/blob/main/meshfiles/x1.655362.grid.nc)?

```Python
import uxarray as ux
import cProfile

profiler = cProfile.Profile()

# Do something here outside of profiler zone
# (i.e. ux.open_grid(...))

profiler.enable()
# Profile something here
profiler.disable()

# Save stats
profiler.dump_stats('results.prof')
```

A screenshot of the `snakeviz results.prof` would be ideal.

2025-02-11 19:30 UTC, rajeeja commented
With correction, takes around twice the time
<img width="1553" alt="Screenshot 2025-02-11 at 13 28 39" src="https://github.com/user-attachments/assets/7e16a1ad-85b9-4687-87f1-f448881e3469" />

Without correction
<img width="1564" alt="Screenshot 2025-02-11 at 13 28 49" src="https://github.com/user-attachments/assets/adac39f0-f34e-481f-8d41-9d3263d6766f" />

Disabled Numba for all of it.

2025-02-11 20:08 UTC, rajeeja commented
@philipc2 thanks for the review and suggestions, here  is the snakeviz output, with numba disabled:

Area Correction:
<img width="1640" alt="Screenshot 2025-02-11 at 13 54 47" src="https://github.com/user-attachments/assets/08faab1e-9de1-4901-b23e-bf0b95262444" />
No Area Correction:
<img width="1355" alt="Screenshot 2025-02-11 at 14 06 21" src="https://github.com/user-attachments/assets/2960bbea-6547-457f-9d30-8f8a74e405b6" />

2025-02-19 22:20 UTC, philipc2 commented
> @philipc2 thanks for the review and suggestions, here is the snakeviz output, with numba disabled:
> 
> Area Correction: <img alt="Screenshot 2025-02-11 at 13 54 47" width="1640" src="https://private-user-images.githubusercontent.com/1466114/412147855-08faab1e-9de1-4901-b23e-bf0b95262444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwMDM4NzAsIm5iZiI6MTc0MDAwMzU3MCwicGF0aCI6Ii8xNDY2MTE0LzQxMjE0Nzg1NS0wOGZhYWIxZS05ZGUxLTQ5MDEtYjIzZS1iZjBiOTUyNjI0NDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMTlUMjIxOTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDZhYzRjM2UwYzI5MmQ4NWYwYTVmYzY4NWNlZjYwZGU0OTkxZmIzZGYxNjI0MDIyNzZiMzQ0YmQyYjE3N2I5YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IGaGGG7TGoEWgM2nl7Cqa2ax9jwYLeSlnisieE6r4hA"> No Area Correction: <img alt="Screenshot 2025-02-11 at 14 06 21" width="1355" src="https://private-user-images.githubusercontent.com/1466114/412148458-2960bbea-6547-457f-9d30-8f8a74e405b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwMDM4NzAsIm5iZiI6MTc0MDAwMzU3MCwicGF0aCI6Ii8xNDY2MTE0LzQxMjE0ODQ1OC0yOTYwYmJlYS02NTQ3LTQ1N2YtOWQzMC04ZjhhNzRlNDA1YjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMTlUMjIxOTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTM3YjEwZTRkYTE2YjZiZDc2OTA2YTNmNGFkZGQxZTQ5NmIxOWQ4NDA1YjQ1MDA4ODAyZjJkOGVlMDk5ZGU1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QgtNA7Frn6qj4WxWUgFoxrVZoUiqBBucpdRppFghHjU">

Do you have any timings with Numba enabled? its good to see that the overhead here isn't large.

2025-02-19 22:28 UTC, rajeeja commented
> Do you have any timings with Numba enabled? its good to see that the overhead here isn't large.

CORRECTION: Elapsed time: 6.34 seconds
NO CORRECTION: 5.53 seconds

2025-02-19 23:11 UTC, philipc2 commented
> > Do you have any timings with Numba enabled? its good to see that the overhead here isn't large.
> 
> CORRECTION: Elapsed time: 6.34 seconds NO CORRECTION: 5.53 seconds

Fantastic!

2025-02-24 05:36 UTC, philipc2 commented on uxarray/grid/grid.py
> +        correct_area: Optional[bool] = False,
Include the parameter in the docstring.

2025-02-24 05:36 UTC, philipc2 commented on uxarray/grid/grid.py
> +        correct_area: Optional[bool] = False,
Include the parameter in the docstring.

2025-02-25 06:45 UTC, hongyuchen1030 commented on uxarray/grid/area.py
>      coords_type : str, optional
What happen to the input xyz if the `coords_type` is spherical?

2025-02-25 06:45 UTC, hongyuchen1030 commented on uxarray/grid/area.py
> +    if coords_type == "spherical":
Probably refer to how @philipc2 did about the coordinate conversion will be better.

The area correction function will only take cartesian xyz as input. And a wrapper/pretreatment function can be used before calling the area correction to handle the coordinate conversion if needed.

Uxarray is using all cartesian coordinates for internal algorithms anyway. The spherical coordinates is mostly for users

2025-02-25 06:45 UTC, hongyuchen1030 commented on uxarray/grid/area.py
> +            # Check if z-coordinates are approximately equal
Having identical z-coordinates does not guarantee a constant latitude. A great circle arc (GCA) may still be formed—even in non-equatorial or pole-crossing scenarios—as we discussed previously.


Is there any other additional check here to see if it's a constant latitude?

2025-02-25 06:45 UTC, hongyuchen1030 commented on uxarray/grid/area.py
> +                    # Convert Cartesian coordinates to longitude
We always pick the "smallest"  great circle. Which means the edge is not directional. And we will pick the one that has the smallest longitude. (This will end up with swapping the nodes if needed)

2025-02-25 06:50 UTC, hongyuchen1030 commented on uxarray/grid/area.py
> +    den2 = x1 * x2 + y1 * y2
To save some extra operations, consider following order with proper comments
```python
dop_term = x1 * y2 - x2 * y1
denom_2 = x1 * x2 + y1 * y2
denom_1 = x1**2 + y1**2 + denom_2
```

2025-02-25 07:54 UTC, rajeeja commented on uxarray/grid/area.py
>      coords_type : str, optional
see below, as you point out.

2025-02-25 07:54 UTC, rajeeja commented on uxarray/grid/area.py
> +    if coords_type == "spherical":
Can be done, but this is general area correction stuff and can be addressed later, not a subject of this PR.

2025-02-25 07:57 UTC, hongyuchen1030 commented on uxarray/grid/area.py
>      coords_type : str, optional
my point is it will be confusing if the coords_type is spherical but the input name is x y z (but in spherical you will only have lat and lon)

Either change the parameters name or at least put some detailed description in the docstring

2025-02-25 09:24 UTC, rajeeja commented on uxarray/grid/area.py
>      coords_type : str, optional
I get it, just that it'd be good for another PR. See usage [here](https://github.com/UXARRAY/uxarray/pull/1120/files#diff-b49076b32f4b332dcc526498a5e8d299bc1f870d843b9599b5a949804386fcabR61)

2025-02-25 09:45 UTC, rajeeja commented on uxarray/grid/area.py
> +            # Check if z-coordinates are approximately equal
Right, please review again. I have added another check. 
So, we have the following checks for Constant Latitude:
a. The z-coordinates of both endpoints are the same.
b. The edge does not cross the poles or span more than 180 degrees of longitude.

2025-02-25 09:46 UTC, rajeeja commented on uxarray/grid/area.py
> +                    # Adjust for the case where longitude wraps around the 180° meridian
will handle it in another PR, will remove some feature and test associated.

2025-02-25 09:48 UTC, rajeeja commented on uxarray/grid/area.py
> +    n = n / np.linalg.norm(n)
good catch, not needed here.

2025-02-25 09:52 UTC, rajeeja commented on uxarray/grid/area.py
> +    # Calculate the position vector dF
can/should be done, but for another PR.

2025-02-26 18:39 UTC, hongyuchen1030 commented on uxarray/grid/area.py
> +            # Check if z-coordinates are approximately equal
Discussed in slack. These checks didn't hold.

2025-02-26 18:40 UTC, hongyuchen1030 commented on uxarray/grid/area.py
>      coords_type : str, optional
Please at least include a detailed docstring specifying the limitations here. Otherwise it will create confusion in the future development.

2025-02-26 18:43 UTC, hongyuchen1030 commented on uxarray/grid/area.py
> +    if coords_type == "spherical":
@philipc2 Do you think the current implementation is fine for this release? I am worrying that once we call this function in zonal average and calculate huge amounts of faces, it might cause performance issues here and we need to redesign the codes again and again.

2025-02-26 18:43 UTC, hongyuchen1030 commented on uxarray/grid/area.py
> +                    # Adjust for the case where longitude wraps around the 180° meridian
Same here, for the performance concern. @philipc2

2025-03-03 23:14 UTC, rajeeja commented on uxarray/grid/area.py
>      coords_type : str, optional
Done, added a TODO.

2025-03-06 23:29 UTC, philipc2 requested changes
I'm happy to move forward and merge this in its current state. However, please compile an issue for changes that need to me made in the future. 

Please populate the overview markdown for this PR.

2025-03-10 17:27 UTC, merged