Data Access Usage Example
UXARRAY/uxarray pull request #137
Opened 2022-09-19 17:17 UTC by philipc2

Usage Example showcasing different ways of accessing data stored in `Grid` objects. 

1. Indexing with Original Name 
2. UGRID access attributes
3. Indexing with Variable Dictionary

2022-09-19 17:19 UTC, philipc2 commented
@erogluorhan 

Any comments on the general structured of the notebook before I add any text cells / background info?

2022-09-19 18:40 UTC, erogluorhan commented
> @erogluorhan
> 
> Any comments on the general structured of the notebook before I add any text cells / background info?

I cannot see your notebook in the rendered docs. I can't see Anissa's examples page improvements either.

2022-09-19 19:58 UTC, erogluorhan commented
> > > @erogluorhan
> > > Any comments on the general structured of the notebook before I add any text cells / background info?
> > 
> > 
> > I cannot see your notebook in the rendered docs. I can't see Anissa's examples page improvements either.
> 
> Should be fixed now!

Docs generation is failing; please fix.

2022-09-20 18:55 UTC, anissa111 commented
@philipc2 I've added the example to the gallery.yml file, that should make it show up on the examples page!

2022-09-26 21:59 UTC, erogluorhan requested changes
I've put a few inline comments. We may need to play with the entire structure of the notebook.  I am happy to walk you through my thoughts in a short meeting if you want.

2022-09-26 21:59 UTC, erogluorhan commented on docs/examples/data-access.ipynb
> +    "There are many different conventions used to define unstructured grids (UGRID, SCRIP, etc.). These conventions often have different variable names used to describe the same variables.\n",
Slight correction: "There are many different grid types ..."

Remove: "These conventions often have different variable names used to describe the same variables"

2022-09-26 21:59 UTC, erogluorhan commented on docs/examples/data-access.ipynb
> +    "non_ugrid_grid_path = base_path + \"geoflow-small/grid.nc\""
This is actually a UGRID file with different variable namings. We might need to modify the entire structure of the notebook.

2022-09-26 21:59 UTC, erogluorhan commented on docs/examples/data-access.ipynb
> +    "UXarray offers multiple ways of accessing data stored in `Grid` objects. This notebook will highlight different ways of accessing data with examples both in UGRID and non-UGRID formats.\n",
Tell something about the facts that 

(1) whatever the grid type UXarray reads in, it converts it to a UGRID type in the Grid object.  
(2) The UGRID convention is flexible about variable namings except a few required topology attributes (such as "cf_role", "topology_dimension", etc.)
(3) To handle all of those variable names coming from either non-UGRID or UGRID types, UXarray Grid object makes use of a dictionary in which it uses a set of standardized names for keys and custom names as values.
      - There are a few different ways to access those variables in UXarray Grid object.

2022-10-03 23:19 UTC, philipc2 commented
@erogluorhan @rajeeja 

New notebook is pushed. Addressed most of the comments from our meeting last week. Let me know if this new layout works better. 

I'm also considering adding a short blurb about UGRID conventions with a diagram, would that be a good addition?

2022-10-03 23:20 UTC, rajeeja commented
😊 diagrams, yay!

2022-10-27 23:18 UTC, erogluorhan commented
Close in favor of PR #164

2022-10-27 23:18 UTC, closed without merging