area  calculation notebook
UXARRAY/uxarray pull request #285
Opened 2023-04-18 20:22 UTC by rajeeja

2023-04-18 22:17 UTC, anissa111 commented
@philipc2 I'm taking a look now!

2023-04-18 22:17 UTC, anissa111 commented
(Sorry wrong button!!)

2023-04-18 22:26 UTC, anissa111 commented
Yeah, okay so it's nothing to do with this PR specifically. In `contributing.rst`, we use internal links to link to different section headings. One of the links doesn't have a corresponding heading because, I think, we skipped a number. 

<img width="823" alt="image" src="https://user-images.githubusercontent.com/38434768/232918436-8ad507f3-3762-4cdc-8f8c-5780a34f9570.png">

No idea why it's failing on this now instead of earlier, but there you go!

2023-04-19 03:58 UTC, rajeeja commented
Thanks @anissa111 
Had to open the notebook in an editor and remove tensorflow (my local conda env name) in name/display_name `metadata` section of python notebook. 

Seems to be fine now, please review

2023-04-19 15:44 UTC, philipc2 requested changes
Looks good so far, please give it another read through for typos.

Can you also move major comment blocks into markdown cells for better readability (see our other example notebooks as a reference).

2023-04-19 15:44 UTC, philipc2 commented on docs/examples/003-area-calc.ipynb
> +    "**This notebook has teh following sections:**\n",
```suggestion
    "**This notebook has the following sections:**\n",
```

2023-04-19 15:44 UTC, philipc2 commented on docs/examples/003-area-calc.ipynb
> +    "# Calculating face area(s) with UXarray\n",
I suggest using a simpler name, maybe the following?

```suggestion
    "# Face Area Calculations\n",
```

2023-04-19 15:44 UTC, philipc2 commented on docs/examples/003-area-calc.ipynb
> +    "## 2. Options for calculate_total_face_area functions\n",
```suggestion
    "## 2. Options for `Grid.calculate_total_face_area` functions\n",
```

2023-04-19 15:44 UTC, philipc2 commented on docs/examples/003-area-calc.ipynb
> +    "We will be using outCSne30.ug grid file, that follow the UGRID convention.\n",
```suggestion
    "We will be using the `outCSne30.ug` grid file which is encoded in the UGRID convention.\n",
```

2023-04-19 16:19 UTC, erogluorhan reviewed
Thanks for putting this together! Please see my inline comments.

2023-04-19 16:19 UTC, erogluorhan commented on docs/gallery.yml
> +- title: Calculating face area(s) with UXarray
I'd recommend to remove "with UXarray".

2023-04-19 16:19 UTC, erogluorhan commented on docs/examples/003-area-calc.ipynb
> +    "example](https://uxarray.readthedocs.io/en/latest/examples/read-grid-data.html)\n",
This link is broken

2023-04-19 16:19 UTC, erogluorhan commented on docs/examples/003-area-calc.ipynb
> +    "the grid topology attributes and variables stored in the `UXarray.Grid`\n",
"... the grid topology ..." may need to be rephrased, was the intent to say something like ""... through grid topology ...""?

2023-04-19 16:19 UTC, erogluorhan commented on docs/examples/003-area-calc.ipynb
> +    "3. Getting area of all the faces (not total)\n",
Maybe say "3. Getting individual areas of each face \n" or "3. Getting areas of all the indivdual faces \n" instead?

2023-04-19 16:19 UTC, erogluorhan commented on docs/examples/003-area-calc.ipynb
> +    "# 4 Pi is the area 4*3.14 = 12.56"
"4*pi"

2023-04-19 16:53 UTC, rajeeja commented on docs/examples/003-area-calc.ipynb
> +    "verts_grid.face_areas"
not a typing errror, this is something that works with 

`
config.DISABLE_JIT = True
`

Numba doesn't like something. Also, there is another issue with providing a grid without z-cords, that also fails.
Debugging this is hard, trying to see what's wrong.

I am planning to introduce a couple more options with helpers that would not rely on UXarray loaded grid to this file:

ux.helpers.calculate_face_area
and
ux. helpers.get_all_face_area_from_coords

2023-04-20 05:24 UTC, erogluorhan approved these changes

2023-04-20 17:29 UTC, philipc2 approved these changes

2023-04-20 17:29 UTC, merged