Accurate dot product and accurate operation utils
UXARRAY/uxarray pull request #557
Opened 2023-10-27 20:38 UTC by hongyuchen1030

Closes #XXX

## Overview

In this PR, we have organized and enhanced the utilities for accurate computing within uxarray. All functions related to accurate computing have been consolidated into a single file, `uxarray.grid.accurate_computing_utils.py,` for better maintainability and clarity. 

Additionally, I have implemented a more precise method for dot product calculations, utilizing Fused Multiply-Add (FMA) operations to improve the accuracy and reliability of the results.
## Expected Usage

```Python
import uxarray as ux

grid_path = "/path/to/grid.nc"
data_path = "/path/to/data.nc"

# Opening the dataset using uxarray
uxds = ux.open_dataset(grid_path, data_path)

# Utilizing the accurate dot product function
result = uxds.accurate_dot_product(vector_a, vector_b)

# Employing other accurate computing utilities
output = uxds.some_accurate_computing_function(param1, param2)

```

## PR Checklist

**General**
- [ ] An issue is linked created and linked
- [ ] Add appropriate labels
- [ ] Filled out Overview and Expected Usage (if applicable) sections

**Testing**
- [ ] Adequate tests are created if there is new functionality
- [ ] Tests cover all possible logical paths in your function
- [ ] Tests are not too basic (such as simply calling a function and nothing else)

**Documentation**
- [ ] Docstrings have been added to all new functions
- [ ] Docstrings have updated with any function changes
- [ ] Internal functions have a preceding underscore (`_`) and have been added to `docs/internal_api/index.rst`
- [ ] User functions have been added to `docs/user_api/index.rst`

**Examples**
- [ ] Any new notebook examples added to `docs/examples/` folder
- [ ] Clear the output of all cells before committing
- [ ] New notebook files added to `docs/examples.rst` toctree
- [ ] New notebook files added to new entry in `docs/gallery.yml` with appropriate thumbnail photo in `docs/_static/thumbnails/`

2023-10-27 21:28 UTC, philipc2 reviewed
I think this is a great change.

Can we think of a different module name though, preferably without the `utils` suffix.

Also, I don't think these should be under the `grid` directory, since I can see these being useful elsewhere too (i.e. within a DataArray)

I'll think of a good name and get back to you

2023-10-27 21:34 UTC, hongyuchen1030 commented
> I think this is a great change.
> 
> Can we think of a different module name though, preferably without the `utils` suffix.
> 
> Also, I don't think these should be under the `grid` directory, since I can see these being useful elsewhere too (i.e. within a DataArray)
> 
> I'll think of a good name and get back to you

Thank you very much for your help. And I just wanted to bring the ideas on the table now and I am also looking for a more appropriate arrangement and name. please let me know if you have any problems

2023-10-30 17:34 UTC, hongyuchen1030 commented
> How about we move these into a `computing.py` under the `uxarray.utils` directory?
> 
> This would lead to imports like:
> 
> ```python
> from uxarray.utils.computing import dot_fma
> ```

Thank you for your suggestion! However, I am thinking about if we should keep the work "accurate" here? The term accurate refers to this series of floating point operations that provide high accuracy. For example, [accupy](https://github.com/sigma-py/accupy)

2023-10-30 20:34 UTC, philipc2 commented
> > How about we move these into a `computing.py` under the `uxarray.utils` directory?
> > This would lead to imports like:
> > ```python
> > from uxarray.utils.computing import dot_fma
> > ```
> 
> Thank you for your suggestion! However, I am thinking about if we should keep the word "accurate" here? The term accurate refers to this series of floating point operations that provide high accuracy. For example, [accupy](https://github.com/sigma-py/accupy)

It's typically not suggested to use multiple words in a module name, such as `accurate_computing_utils.py` The "accurate" aspect can be described in our documentation or through usage examples, since most, if not all, of the uses of these functions will still be only used internally.

2023-10-30 22:31 UTC, hongyuchen1030 commented
> > > How about we move these into a `computing.py` under the `uxarray.utils` directory?
> > > This would lead to imports like:
> > > ```python
> > > from uxarray.utils.computing import dot_fma
> > > ```
> > 
> > 
> > Thank you for your suggestion! However, I am thinking about if we should keep the word "accurate" here? The term accurate refers to this series of floating point operations that provide high accuracy. For example, [accupy](https://github.com/sigma-py/accupy)
> 
> It's typically not suggested to use multiple words in a module name, such as `accurate_computing_utils.py` The "accurate" aspect can be described in our documentation or through usage examples, since most, if not all, of the uses of these functions will still be only used internally.

Thank you for your information, it works for me.

2023-11-08 21:30 UTC, philipc2 requested changes
Looks good to me. Will approve once these are corrected!

2023-11-08 21:30 UTC, philipc2 commented on docs/user_api/index.rst
> +   grid.accurate_computing_utils.dot_fma
```suggestion
   grid.utils.computing.cross_fma
   grid.utils.computing.dot_fma
```

2023-11-10 08:15 UTC, philipc2 approved these changes
These are some great additions!

2023-11-10 08:16 UTC, merged