DRAFT: E3SM UXarray and Dask Examples
UXARRAY/uxarray pull request #836
Opened 2024-07-03 18:50 UTC by rytam2

Closes #XXX

## Overview

## Expected Usage

```Python
import uxarray as ux

grid_path = "/path/to/grid.nc"
data_path = "/path/to/data.nc"

uxds = ux.open_dataset(grid_path, data_path)

# this is how you use this function
some_output = uxds.some_function()

# this is another way to use this function
other_output = uxds.some_function(some_param = True)

```

## PR Checklist

**General**
- [ ] An issue is linked created and linked
- [ ] Add appropriate labels
- [ ] Filled out Overview and Expected Usage (if applicable) sections

**Testing**
- [ ] Adequate tests are created if there is new functionality
- [ ] Tests cover all possible logical paths in your function
- [ ] Tests are not too basic (such as simply calling a function and nothing else)

**Documentation**
- [ ] Docstrings have been added to all new functions
- [ ] Docstrings have updated with any function changes
- [ ] Internal functions have a preceding underscore (`_`) and have been added to `docs/internal_api/index.rst`
- [ ] User functions have been added to `docs/user_api/index.rst`

**Examples**
- [ ] Any new notebook examples added to `docs/examples/` folder
- [ ] Clear the output of all cells before committing
- [ ] New notebook files added to `docs/examples.rst` toctree
- [ ] New notebook files added to new entry in `docs/gallery.yml` with appropriate thumbnail photo in `docs/_static/thumbnails/`

2024-07-08 22:16 UTC, rytam2 commented
<p>Hi Philip, thanks for the comment! For the syntax, do you mean I'll do the following: </p>

<pre class="ql-syntax" spellcheck="false">$$
{SWCRE = FSNT-FSNTC}
$$
</pre><p>Or do you mean adding <code>{math}</code> before the <code>SWCRE...FSNTC</code> equation, and have <code>$$</code> removed?  </p>

---

 <a href='https://app.reviewnb.com/UXARRAY/uxarray/pull/836/discussion/#comment-2214665974'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-07-09 06:22 UTC, philipc2 commented
<p>Correct, it should look like {math}{SWCRE = FSNT - FSNTC}</p>

---

 <a href='https://app.reviewnb.com/UXARRAY/uxarray/pull/836/discussion/#comment-2214665974'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-07-11 21:46 UTC, philipc2 commented
Looks like the LaTex is still broken. Can you add the following to our `conf.py` and see if it fixes things? 

https://github.com/UXARRAY/uxarray/blob/main/docs/conf.py

```Python
myst_enable_extensions = [
    "amsmath",
    "attrs_inline",
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]
```

2024-07-12 16:40 UTC, philipc2 commented
@rytam2 

Now that you've marked the PR as ready for review, there's a few things that you can also do: 
- Remove the DRAFT from the title 
- Add reviewers (can add orhan, rajeev, aaron and myself) 

<img width="408" alt="image" src="https://github.com/user-attachments/assets/86082548-adeb-4137-884c-b6a5f32279b3">

2024-07-12 17:25 UTC, philipc2 commented
@anissa111 

Any idea on why LatEx isn't rendering correctly in the notebooks? We've tried a few things above but are still having some issues.

2024-07-12 17:30 UTC, anissa111 commented
> @anissa111
> 
> Any idea on why LatEx isn't rendering correctly in the notebooks? We've tried a few things above but are still having some issues.

I'll take a look!

2024-07-12 18:42 UTC, anissa111 commented
Okay, locally either

````
```{math}
	SWCRE = FSNT - FSNTC
```
````

or

```
$$
	SWCRE = FSNT - FSNTC
$$
```

Works for me

2024-07-17 21:14 UTC, rytam2 commented
<p>Now updated with cluster usage. </p>

---

 <a href='https://app.reviewnb.com/UXARRAY/uxarray/pull/836/discussion/#comment-2232052027'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-07-17 21:15 UTC, rytam2 commented
<p>Moved above prior to closing cluster.</p>

---

 <a href='https://app.reviewnb.com/UXARRAY/uxarray/pull/836/discussion/#comment-2232052042'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-07-22 20:10 UTC, erogluorhan reviewed
Great additions! I have some inline and ReviewNB comments below

2024-07-25 17:36 UTC, philipc2 commented on docs/conf.py
> +]
We can change this back to the name of the notebooks, without the paths.

2024-07-26 04:22 UTC, rytam2 commented
<p>Added paragraph from zulip discussion. </p>

---

 <a href='https://app.reviewnb.com/UXARRAY/uxarray/pull/836/discussion/#comment-2243731037'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-08-12 18:54 UTC, rajeeja commented
We might want to think about changing the name of `Gallery` - that houses two of the notebooks in this PR.

The formatting of equations for the below: don't look good://
<img width="816" alt="Screenshot 2024-08-12 at 13 51 03" src="https://github.com/user-attachments/assets/19892347-28d6-48fd-b1f4-3e904aa96adc">
//

2024-08-12 19:00 UTC, philipc2 commented
> We might want to think about changing the name of `Gallery` - that houses two of the notebooks in this PR.
> 
> The formatting of equations for the below: don't look good:// <img alt="Screenshot 2024-08-12 at 13 51 03" width="816" src="https://private-user-images.githubusercontent.com/1466114/357167701-19892347-28d6-48fd-b1f4-3e904aa96adc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0ODkzNjksIm5iZiI6MTcyMzQ4OTA2OSwicGF0aCI6Ii8xNDY2MTE0LzM1NzE2NzcwMS0xOTg5MjM0Ny0yOGQ2LTQ4ZmQtYjFmNC0zZTkwNGFhOTZhZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMTg1NzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmM5NTIyNGNlMGRlY2ExY2JhZjMwMDkwZTVjM2U1NzU4ZmFhM2IwZjhjNmZlNTVjYThmYTc4MzMxYzAwNTExZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lyKzw8dqN8KtV51H_zweTfRxihJ8d2l9Mh2ZMsG4z-Q"> //

The Gallery can house both Workflow & Visualization examples. Do you think this sepperation is appropriate? 

![image](https://github.com/user-attachments/assets/3185ec71-5e7a-47ef-b326-895944f4c879)

The equations look like this for me in the rendered docs in light mode. 

![image](https://github.com/user-attachments/assets/646afd41-94b3-47f5-a973-125821a4a948)


Looks like they are broken with the Dark Mode.

![image](https://github.com/user-attachments/assets/682f08ec-752d-4e2e-851a-1a0e77854936)

Have you ever encountered this @anissa111 ?

2024-08-12 19:52 UTC, anissa111 commented
I haven't actually. 

I poked around for a bit and suggest starting at this [stackoverflow post](https://stackoverflow.com/questions/11096214/color-in-mathjax) and here in [mathjax documentation](https://docs.mathjax.org/en/v2.2-latest/CSS-styles.html).

Let me know what you find!

2024-08-12 20:37 UTC, rljacob commented
I think of "gallery" as just being images/viz.

2024-08-13 03:00 UTC, rajeeja requested changes
see comments in e3sm-load notebook.

2024-08-28 01:13 UTC, philipc2 requested changes
Apologies for the long gap in reviews! I've left a few suggestions here. Once we've resolved all the ReviewNB comments, we should be good to go!

2024-08-28 01:13 UTC, philipc2 commented on docs/userguide.rst
> +`Loading Data with Dask <user-guide/parallel-load-ux-with-dask.ipynb>`_
```suggestion
`Loading Data using Dask <user-guide/parallel-load-ux-with-dask.ipynb>`_
```

2024-08-28 01:13 UTC, philipc2 commented on docs/gallery.yml
> +  - title: Plotting E3SMv2 Output with UXarray
E3SMv2 Output
```suggestion
  - title: E3SMv2 Model Output Visualizations 
```

2024-08-28 01:13 UTC, philipc2 commented on docs/gallery.yml
> +  - title:  Calculations on E3SMv2 Output with UXarray
An idea for a more descriptive title, any thoughts? 

```suggestion
  - title:  Radiative Feedback Analysis on E3SMv2 Model Output
```

2024-08-30 17:51 UTC, rytam2 commented
<p>Now updated with link.</p>

---

 <a href='https://app.reviewnb.com/UXARRAY/uxarray/pull/836/discussion/#comment-2253217159'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-08-30 17:52 UTC, rytam2 commented
<p>Updated</p>

---

 <a href='https://app.reviewnb.com/UXARRAY/uxarray/pull/836/discussion/#comment-2253217174'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-08-30 20:35 UTC, rytam2 commented
<p>Related to bug in <code>.plot.rasterize</code> that requires a name to plot; will keep this line as a temporary solution.  </p>

---

 <a href='https://app.reviewnb.com/UXARRAY/uxarray/pull/836/discussion/#comment-2252958987'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-10-08 22:49 UTC, philipc2 requested changes
Excellent work Rachel! I've put a few comments in ReviewNB.

May we change the thumbnail to one of the projected ones?

<img width="578" alt="image" src="https://github.com/user-attachments/assets/6af8e1d1-b998-4b0b-b8d2-728d4202c427">


I'd also consider a thumbnail for the e3sm calc notebook.

2024-10-09 20:32 UTC, rytam2 commented
<p>accepted</p>

---

 <a href='https://app.reviewnb.com/UXARRAY/uxarray/pull/836/discussion/#comment-2400949092'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-10-23 00:00 UTC, philipc2 approved these changes
Great work Rachel!

2024-10-23 00:01 UTC, merged