DRAFT: Merge Duplicate Node Indices
UXARRAY/uxarray pull request #879
Opened 2024-08-06 17:20 UTC by philipc2

Closes #XXX

## Overview

## Expected Usage

```Python
import uxarray as ux

grid_path = "/path/to/grid.nc"

uxgrid = ux.open_grid(grid_path)

# inplace
uxgrid.merge_duplicate_node_indices()

# return a new grid
new_grid = uxgrid.merge_duplicate_node_indices(inplace=False)

```

2024-08-06 21:26 UTC, aaronzedwick commented
Do you know what the problem was with the previous implementation? If I remember it was still having problems?

2024-08-12 18:28 UTC, philipc2 commented
> Do you know what the problem was with the previous implementation? If I remember it was still having problems?

I haven't been able to pinpoint the problem, but everything appears to be working correctly here according to the tests.

2024-08-12 20:57 UTC, philipc2 commented
@aaronzedwick 

I'm going to merge these changes into the branch used in #859 to see the compatibility.

2024-08-12 21:18 UTC, philipc2 commented
@aaronzedwick 

May you take a look at the case using the `geos` dataset? Looks like something is breaking in the `construct_faces` function call.

2024-08-12 21:20 UTC, rajeeja commented
what tests are failing? we may want to issue a warning on how and what is supported.
Supporting all formats may be harder and might break with corner cases.

2024-08-12 21:30 UTC, philipc2 commented
> what tests are failing? we may want to issue a warning on how and what is supported. Supporting all formats may be harder and might break with corner cases.

Something with the Dual Mesh Construction on the Cube Sphere grid is breaking. It's complaining about a dimension miss match when assigned the faces. 

I don't believe it's an issue with how we are merging ndoes.

2024-08-12 21:33 UTC, aaronzedwick commented
> @aaronzedwick
> 
> May you take a look at the case using the `geos` dataset? Looks like something is breaking in the `construct_faces` function call.

Oh yeah, I know the problem. Let me fix it for you.

2024-08-12 21:53 UTC, aaronzedwick commented
@philipc2 There you go!

2024-08-12 21:54 UTC, philipc2 commented
> @philipc2 There you go!

Thanks for fixing this so quickly!

2024-08-12 22:08 UTC, philipc2 commented
@aaronzedwick 

There still appear to be some underlying issues, at least on the Cube Sphere grid.

Running the following executes, however when I try to plot it I get the following error:

```Python
uxgrid.merge_duplicate_node_indices(inplace=True)
dual = uxgrid.compute_dual()
```

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[18], line 1
----> 1 dual.plot()

File ~/anaconda3/envs/dev-uxarray/lib/python3.11/site-packages/uxarray/plot/accessor.py:30, in GridPlotAccessor.__call__(self, **kwargs)
     29 def __call__(self, **kwargs) -> Any:
---> 30     return grid_plot.plot(self._uxgrid, **kwargs)

File ~/anaconda3/envs/dev-uxarray/lib/python3.11/site-packages/uxarray/plot/grid_plot.py:16, in plot(grid, **kwargs)
     14 def plot(grid: Grid, **kwargs):
     15     """Default Plotting Method for Grid."""
---> 16     return mesh(grid, **kwargs)

File ~/anaconda3/envs/dev-uxarray/lib/python3.11/site-packages/uxarray/plot/grid_plot.py:43, in mesh(uxgrid, backend, exclude_antimeridian, width, height, xlabel, ylabel, **kwargs)
     19 def mesh(
     20     uxgrid: Grid,
     21     backend: Optional[str] = "bokeh",
   (...)
     27     **kwargs,
     28 ):
     29     """Vector Line Plot of the edges that make up each face.
     30 
     31     Parameters
   (...)
     40         Plot Width for Bokeh Backend
     41     """
---> 43     gdf = uxgrid.to_geodataframe(exclude_antimeridian=exclude_antimeridian)
     45     hv_paths = hv.Path(gdf)
     47     uxarray.plot.utils.backend.assign(backend=backend)

File ~/anaconda3/envs/dev-uxarray/lib/python3.11/site-packages/uxarray/grid/grid.py:1304, in Grid.to_geodataframe(self, override, cache, exclude_antimeridian)
   1301     return self._gdf
   1303 # construct a geodataframe with the faces stored as polygons as the geometry
-> 1304 gdf = _grid_to_polygon_geodataframe(
   1305     self, exclude_antimeridian=exclude_antimeridian
   1306 )
   1308 # cache computed geodataframe
   1309 if cache:

File ~/anaconda3/envs/dev-uxarray/lib/python3.11/site-packages/uxarray/grid/geometry.py:95, in _grid_to_polygon_geodataframe(grid, exclude_antimeridian)
     91 def _grid_to_polygon_geodataframe(grid, exclude_antimeridian):
     92     """Converts the faces of a ``Grid`` into a ``spatialpandas.GeoDataFrame``
     93     with a geometry column of polygons."""
---> 95     polygon_shells = _build_polygon_shells(
     96         grid.node_lon.values,
     97         grid.node_lat.values,
     98         grid.face_node_connectivity.values,
     99         grid.n_face,
    100         grid.n_max_face_nodes,
    101         grid.n_nodes_per_face.values,
    102     )
    104     antimeridian_face_indices = _build_antimeridian_face_indices(
    105         polygon_shells[:, :, 0]
    106     )
    108     if grid.n_face > GDF_POLYGON_THRESHOLD:

File ~/anaconda3/envs/dev-uxarray/lib/python3.11/site-packages/uxarray/grid/geometry.py:82, in _build_polygon_shells(node_lon, node_lat, face_node_connectivity, n_face, n_max_face_nodes, n_nodes_per_face, projection)
     77     node_lon = lonlat_proj[:, 0]
     78     node_lat = lonlat_proj[:, 1]
     80 polygon_shells = (
     81     np.array(
---> 82         [node_lon[closed_face_nodes], node_lat[closed_face_nodes]], dtype=np.float32
     83     )
     84     .swapaxes(0, 1)
     85     .swapaxes(1, 2)
     86 )
     88 return polygon_shells

IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 864


Some of the entries in the `face_node_connectivity` are now incorrect. There are some entries that are an entire row of fill values. 

The number of entirely zero entries corresponds to how many duplicates were found.

<img width="529" alt="image" src="https://github.com/user-attachments/assets/3e2af8d4-95bb-43ab-99fb-241300add220">

Instead of having rows of full fill values, we should ensure that each duplicate has the same entry in the connectivity.

2024-08-13 14:53 UTC, aaronzedwick commented
@philipc2 I am not exactly sure what's happening, but I don't believe its a problem with my code. The only reason you are getting that error is because the connectivity that you are passing in is broken I think. Comment out the line in construct_faces that says if `n_edges[i] < 3: continue` and then compute dual will run, and the plot is still incorrect. All those fill value entries look to only have one node for some reason around which it is trying to make a dual face. Something with the `node_face_connectivity` I suppose?

2024-08-13 17:20 UTC, philipc2 commented
> @philipc2 I am not exactly sure what's happening, but I don't believe its a problem with my code. The only reason you are getting that error is because the connectivity that you are passing in is broken I think. Comment out the line in construct_faces that says if `n_edges[i] < 3: continue` and then compute dual will run, and the plot is still incorrect. All those fill value entries look to only have one node for some reason around which it is trying to make a dual face. Something with the `node_face_connectivity` I suppose?

Yeah that seems to be the case, I'll look into it!

2024-08-13 19:33 UTC, philipc2 commented
> @philipc2 I am not exactly sure what's happening, but I don't believe its a problem with my code. The only reason you are getting that error is because the connectivity that you are passing in is broken I think. Comment out the line in construct_faces that says if `n_edges[i] < 3: continue` and then compute dual will run, and the plot is still incorrect. All those fill value entries look to only have one node for some reason around which it is trying to make a dual face. Something with the `node_face_connectivity` I suppose?

Something still appears to be off, I'm getting the same error now (even though the connectivity appears to have been corrected) 

![image](https://github.com/user-attachments/assets/983c1dee-c29f-4414-bded-d6c1f729dc74)

2024-08-13 19:49 UTC, aaronzedwick commented
Can you push the changes that fixed the connectivity?

2024-08-30 20:20 UTC, rajeeja requested changes
just one minor test and this is good go.

2024-08-30 20:20 UTC, rajeeja commented on test/test_grid.py
> +        uxgrid.merge_duplicate_node_indices()
add an assert to check that `compute_dual` fails or produces incorrect stuff without this operation.

2024-11-21 19:10 UTC, closed without merging